[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "pnpm migrate && pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
healthcheckInterval = 15
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[build.args]
NODE_VERSION = "18"

[build.environment]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[service]
name = "darvaya-ai-chatbot"

# Configure the service to use the latest Node.js LTS
[service.runtime]
nodeVersion = "18"

# Configure the service to use the latest pnpm
[service.packageManager]
name = "pnpm"
version = "latest"

# Configure the service to use the latest pnpm
[service.checks]
http = "/api/health"
interval = "15s"
timeout = "5s"

# Configure the service to use the latest pnpm
[service.scaling]
min = 1
max = 3
targetCpuUtilization = 70
targetMemoryUtilization = 80